#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD9631FEAF0CC6227 (infra-root@openstack.org)
#
Name     : python-cinderclient
Version  : 1.9.0
Release  : 27
URL      : http://tarballs.openstack.org/python-cinderclient/python-cinderclient-1.9.0.tar.gz
Source0  : http://tarballs.openstack.org/python-cinderclient/python-cinderclient-1.9.0.tar.gz
Source99 : http://tarballs.openstack.org/python-cinderclient/python-cinderclient-1.9.0.tar.gz.asc
Summary  : OpenStack Block Storage API Client Library
Group    : Development/Tools
License  : Apache-2.0
Requires: python-cinderclient-bin
Requires: python-cinderclient-python
Requires: Babel
Requires: keystoneauth1
Requires: oslo.i18n
Requires: oslo.utils
Requires: pbr
Requires: requests
Requires: simplejson
Requires: six
BuildRequires : configparser-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Python bindings to the OpenStack Cinder API
===========================================

%package bin
Summary: bin components for the python-cinderclient package.
Group: Binaries

%description bin
bin components for the python-cinderclient package.


%package python
Summary: python components for the python-cinderclient package.
Group: Default

%description python
python components for the python-cinderclient package.


%prep
%setup -q -n python-cinderclient-1.9.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489333617
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489333617
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cinder

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
